export const coffeeMenu = [
  {
    name: "Espresso",
    category: "Classic",
    price: 2.5,
    description: "A strong and rich shot of coffee with a bold flavor.",
    photo: "espresso.jpg",
    special: false,
    tag: "Strong",
  },
  {
    name: "Cappuccino",
    category: "Classic",
    price: 3.5,
    description: "A balanced mix of espresso, steamed milk, and foam.",
    photo: "cappuccino.jpg",
    special: true,
    tag: "Creamy",
  },
  {
    name: "Latte",
    category: "Classic",
    price: 3.75,
    description:
      "Smooth and creamy with a perfect blend of espresso and steamed milk.",
    photo: "latte.jpg",
    special: false,
    tag: "Smooth",
  },
  {
    name: "Mocha",
    category: "Chocolate",
    price: 4.0,
    description: "A delicious blend of chocolate, espresso, and steamed milk.",
    photo: "mocha.jpg",
    special: true,
    tag: "Chocolatey",
  },
  {
    name: "Macchiato",
    category: "Classic",
    price: 3.25,
    description: "Espresso marked with a small amount of steamed milk.",
    photo: "macchiato.jpg",
    special: false,
    tag: "Bold",
  },
  {
    name: "Flat White",
    category: "Classic",
    price: 3.5,
    description: "A smooth espresso with a velvety microfoam.",
    photo: "flat_white.jpg",
    special: true,
    tag: "Velvety",
  },
  {
    name: "Americano",
    category: "Classic",
    price: 2.75,
    description: "Espresso diluted with hot water for a milder flavor.",
    photo: "americano.jpg",
    special: false,
    tag: "Mild",
  },
  {
    name: "Affogato",
    category: "Dessert",
    price: 4.5,
    description:
      "A scoop of vanilla ice cream drowned in a shot of hot espresso.",
    photo: "affogato.jpg",
    special: true,
    tag: "Indulgent",
  },
  {
    name: "Cold Brew",
    category: "Cold",
    price: 3.0,
    description: "Smooth and refreshing coffee brewed cold for 12 hours.",
    photo: "cold_brew.jpg",
    special: false,
    tag: "Refreshing",
  },
  {
    name: "Nitro Cold Brew",
    category: "Cold",
    price: 4.0,
    description: "Cold brew infused with nitrogen for a creamy texture.",
    photo: "nitro_cold_brew.jpg",
    special: true,
    tag: "Creamy",
  },
  {
    name: "Iced Latte",
    category: "Cold",
    price: 3.75,
    description: "Chilled espresso with cold milk and ice.",
    photo: "iced_latte.jpg",
    special: false,
    tag: "Chilled",
  },
  {
    name: "Iced Americano",
    category: "Cold",
    price: 2.75,
    description: "Chilled espresso with cold water and ice.",
    photo: "iced_americano.jpg",
    special: false,
    tag: "Light",
  },
  {
    name: "Iced Mocha",
    category: "Cold",
    price: 4.25,
    description: "Cold mocha with chocolate, espresso, and milk over ice.",
    photo: "iced_mocha.jpg",
    special: true,
    tag: "Decadent",
  },
  {
    name: "Caramel Macchiato",
    category: "Specialty",
    price: 4.0,
    description: "Espresso with steamed milk, vanilla, and caramel drizzle.",
    photo: "caramel_macchiato.jpg",
    special: true,
    tag: "Sweet",
  },
  {
    name: "Café au Lait",
    category: "Classic",
    price: 3.0,
    description: "Brewed coffee with steamed milk.",
    photo: "cafe_au_lait.jpg",
    special: false,
    tag: "Classic",
  },
  {
    name: "Irish Coffee",
    category: "Alcoholic",
    price: 5.5,
    description: "Coffee with Irish whiskey, sugar, and topped with cream.",
    photo: "irish_coffee.jpg",
    special: true,
    tag: "Rich",
  },
  {
    name: "Cortado",
    category: "Classic",
    price: 3.0,
    description:
      "Equal parts espresso and steamed milk for a strong yet smooth drink.",
    photo: "cortado.jpg",
    special: false,
    tag: "Balanced",
  },
  {
    name: "Turkish Coffee",
    category: "Specialty",
    price: 3.5,
    description:
      "Rich, unfiltered coffee with a strong flavor, often sweetened.",
    photo: "turkish_coffee.jpg",
    special: true,
    tag: "Intense",
  },
  {
    name: "Vietnamese Iced Coffee",
    category: "Cold",
    price: 4.0,
    description: "Strong coffee with sweetened condensed milk over ice.",
    photo: "vietnamese_iced_coffee.jpg",
    special: true,
    tag: "Sweetened",
  },
  {
    name: "Flat White",
    category: "Classic",
    price: 3.75,
    description: "Espresso with microfoam milk for a rich, smooth texture.",
    photo: "flat_white.jpg",
    special: true,
    tag: "Rich",
  },
];

export const person = {
  firstName: "John",
  lastName: "Doe",
  age: 30,
  gender: "Male",
  occupation: "Software Engineer",
  address: {
    street: "123 Main St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94101",
    country: "USA",
  },
  contactDetails: {
    email: "john.doe@example.com",
    phone: "+1 555-1234-567",
    socialMedia: {
      twitter: "@johndoe",
      linkedIn: "linkedin.com/in/johndoe",
      instagram: "@johndoe_insta",
    },
  },
};

export const orders = [
  {
    refNumber: "#123456",
    from: "Alicante Centro",
    date: "2024-08-24",
    status: "Delivered",
  },
  {
    refNumber: "#234567",
    from: "Campello",
    date: "2024-08-23",
    status: "In Transit",
  },
  {
    refNumber: "#345678",
    from: "Villajoyosa",
    date: "2024-08-22",
    status: "Pending",
  },
  {
    refNumber: "#456789",
    from: "Alicante Centro",
    date: "2024-08-21",
    status: "Canceled",
  },
  {
    refNumber: "#567890",
    from: "Campello",
    date: "2024-08-20",
    status: "Delivered",
  },
  {
    refNumber: "#678901",
    from: "Villajoyosa",
    date: "2024-08-19",
    status: "In Transit",
  },
  {
    refNumber: "#789012",
    from: "Alicante Centro",
    date: "2024-08-18",
    status: "Pending",
  },
  {
    refNumber: "#890123",
    from: "Campello",
    date: "2024-08-17",
    status: "Delivered",
  },
  {
    refNumber: "#901234",
    from: "Villajoyosa",
    date: "2024-08-16",
    status: "In Transit",
  },
  {
    refNumber: "#012345",
    from: "Alicante Centro",
    date: "2024-08-15",
    status: "Pending",
  },
];
